services:
  genealogy_server:
    build:
      context: ./genealogy_server
      dockerfile: Dockerfile
    container_name: genealogy_server_container
    ports:
      - "4040:4040"
    depends_on:
      - mongo
      - redis
    restart: always
    networks:
      - genealogy_network

  websocket_server:
    build:
      context: ./websocket_server
      dockerfile: Dockerfile
    container_name: websocket_server_container
    ports:
      - "5500:5500"
    depends_on:
      - genealogy_server
    restart: always
    networks:
      - genealogy_network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    restart: always

    networks:
      - genealogy_network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/db
    restart: always
    networks:
      - genealogy_network

volumes:
  mongo-data:
  redis-data:

networks:
  genealogy_network:
