name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build and push images for genealogy_server and websocket_server
      - name: Build and Push Docker Images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker build -t ${DOCKER_USERNAME}/genealogy_server:latest ./genealogy_server
          docker push ${DOCKER_USERNAME}/genealogy_server:latest
          docker build -t ${DOCKER_USERNAME}/websocket_server:latest ./websocket_server
          docker push ${DOCKER_USERNAME}/websocket_server:latest

      # SSH to server and deploy using docker-compose
      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} <<EOF
            cd /path/to/your/docker-compose/project

            # Pull the latest images
            docker-compose pull genealogy_server
            docker-compose pull websocket_server

            # Recreate and restart services
            docker-compose down
            docker-compose up -d
          EOF
